#!/usr/bin/env bash

# This script can be used to update the cldl.rb files in this directory,
# and in the homebrew-cldl repository which should be cloned into this
# directory.
# The script takes the new version as an argument.
#
# Usage example, updating to version v1.2.3:
# ./update_homebrew_version v1.2.3

VERSION=$1
shasum=$(curl -L https://github.com/jussinokelainen/cldl/archive/refs/tags/"$VERSION".tar.gz | sha256sum)
shasum=${shasum%% *}
empty_shasum="d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed"
if [[ "$shasum" == "$empty_shasum" ]]; then
    printf "\e[31m404\e[0m: https://github.com/jussinokelainen/cldl/archive/refs/tags/%s.tar.gz not found.\n" "$VERSION"
    exit 1
else
    printf "New sha256sum: \e[32m%s\e[0m\n" "$shasum"
fi

read -p "Update formula files? [y/n] " -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

cat <<EOF >cldl.rb
class Cldl < Formula
  desc "Directory based cli todo lists"
  homepage "https://github.com/jussinokelainen/cldl"
  url "https://github.com/jussinokelainen/cldl/archive/refs/tags/$VERSION.tar.gz"
  sha256 "$shasum"
  license "MIT"

  depends_on "go" => :build

  def install
    system "make", "release"
    bin.install "build/cldl"
  end
end
EOF

cp ./cldl.rb ./homebrew-cldl/Formula/cldl.rb
echo "Formula files updated."

message="Updated to version $VERSION"
printf "Commit new cldl.rb in homebrew-cldl with message '\e[32m%s\e[0m'?" "$message"
read -p " [y/n] " -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

cd ./homebrew-cldl/ || exit
git add ./Formula/cldl.rb
git commit -m "$message"
git push
